//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zebra_camera_sdk_sample_application.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ZEBRACAMERASDKSAMPLEAPPLICATION_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDB_DEVICE_AWAKE                150
#define IDB_DEVICE_SLEEP                151
#define IDC_BUTTON_GET_CAMERAS          1000
#define IDC_COMBO1                      1003
#define IDC_COMBO_CAMERA_LIST           1003
#define IDC_SLIDER_BRIGHTNESS           1005
#define IDC_CHECK1                      1006
#define IDC_CHECK_BRIGHTNESSAUTO        1006
#define IDC_CHECK_WHITEBALANCETEMP_AUTO 1006
#define IDC_COMBO2                      1007
#define IDC_COMBO_VIDEO_MODE            1007
#define IDC_CHECK2                      1008
#define IDC_CHECK_PICKLIST_IMAGE_EVENT  1008
#define IDC_EDIT4                       1009
#define IDC_EDIT_BUILD_NUMBER           1009
#define IDC_COMBO_POWER_USER_MODE       1009
#define IDC_RADIO1                      1010
#define IDC_RADIO_IMAGE_BMP             1010
#define IDC_PROGRESS_FIRMWARE_DOWNLOAD  1010
#define IDC_CHECK5                      1011
#define IDC_CHECK_AUTO_SAVE_IMAGE       1011
#define IDC_BUTTON2                     1012
#define IDC_BUTTON_SAVE_IMAGE           1012
#define IDC_EDIT5                       1013
#define IDC_EDIT_DATE_OF_MANUFACTURE    1013
#define IDC_EDIT6                       1014
#define IDC_EDIT_MODEL_NO               1014
#define IDC_EDIT7                       1015
#define IDC_EDIT_FIRMWARE_VERSION       1015
#define IDC_EDIT8                       1016
#define IDC_EDIT_HARDWARE_VERSION       1016
#define IDC_EDIT_BRIGHTNESS             1017
#define IDC_SLIDER_CONTRAST             1018
#define IDC_SLIDER_HUE                  1019
#define IDC_CHECK_EXPOSURE_AUTO         1019
#define IDC_EDIT_CONTRAST               1020
#define IDC_SLIDER_SATURATION           1021
#define IDC_SLIDER_SHARPNESS            1022
#define IDC_SLIDER_WHITEBALANCE         1023
#define IDC_EDIT_DATE_OF_FIRSTPROGRAM   1024
#define IDC_SLIDER_EXPOSURE             1025
#define IDC_BUTTON_SETDEFAULTS          1026
#define IDC_COMBO3                      1027
#define IDC_SLIDER_GAMMA                1027
#define IDC_COMBO4                      1028
#define IDC_COMBO_ILLUMINATION_MODE     1028
#define IDC_COMBO5                      1029
#define IDC_COMBO_ORIENTATION           1029
#define IDC_SLIDER_WB_RED               1029
#define IDC_CHECK3                      1030
#define IDC_CHECK_SNAPSHOT_IMAGE_EVENT  1030
#define IDC_CHECK4                      1031
#define IDC_CHECK_DECODE_IMAGE_EVENT    1031
#define IDC_EDIT9                       1032
#define IDC_EDIT_DATE_OF_SERVICE        1032
#define IDC_EDIT_SERIAL_NO              1033
#define IDC_GROUPBOX_CAMERA_CONFIGURATION 1034
#define IDC_EDIT12                      1035
#define IDC_EDIT_EVENT_TYPE             1035
#define IDC_EDIT13                      1036
#define IDC_EDIT_SIZE                   1036
#define IDC_CHECK_CONTINUOUS_IMAGE_EVENT 1037
#define IDC_STATIC_IMAGE_EVENT_DISPLAY  1038
#define IDC_STATIC_IMAGE_VIEW           1039
#define IDC_EDIT14                      1040
#define IDC_EDIT_FORMAT                 1040
#define IDC_EDIT15                      1041
#define IDC_EDIT_TIMESTAMP              1041
#define IDC_RADIO2                      1042
#define IDC_EDIT1                       1042
#define IDC_EDIT_SAVE_LOCATION          1042
#define IDC_RADIO3                      1043
#define IDC_RADIO_IMAGE_JPEG            1043
#define IDC_SLIDER_GAIN                 1043
#define IDC_BUTTON3                     1044
#define IDC_BUTTON_BROWSE               1044
#define IDC_EDIT_HUE                    1045
#define IDC_COMBO_RED_ILLUMINATION      1045
#define IDC_BUTTON_WRITE_TO_FLASH       1045
#define IDC_EDIT__SATURATION            1046
#define IDC_EDIT_SHARPNESS              1047
#define IDC_EDIT_WB                     1048
#define IDC_PROGRESS1                   1049
#define IDC_PROGRESS_FIRMWARE_UPDATE    1049
#define IDC_EDIT_WB_RED                 1049
#define IDC_BUTTON_SETDEFAULTS2         1050
#define IDC_BUTTON_REBOOT               1050
#define IDC_EDIT_FW_FILE_PATH           1051
#define IDC_BUTTON_FW_BROWSE            1052
#define IDC_BUTTON_FW_LAUNCH            1053
#define IDC_BUTTON_FW_INSTALL           1053
#define IDC_BUTTON_FW_UPDATE            1054
#define IDC_BUTTON_FW_DOWNLOAD          1054
#define IDC_BUTTON_FW_ABORT             1055
#define IDC_EDIT_GAMMA                  1055
#define IDC_EDIT_EXPOSURE               1056
#define IDC_COMBO_WHITE_ILLUMINATION    1057
#define IDC_EDIT_GAIN                   1057
#define IDC_COMBO_IMAGE_RESOLUTION      1058
#define IDC_COMBO_IMAGE_FORMAT          1059
#define IDC_EDIT_IMAGE_RESOLUTION       1060
#define IDC_SLIDER_BACKLIGHT_COMP       1061
#define IDC_EDIT_GAIN2                  1062
#define IDC_EDIT_BACKLIGHT_COMP         1062
#define IDC_BUTTON_FW_BROWSE2           1063
#define IDC_BUTTON_FW_CANCEL            1063
#define IDC_BUTTON_CAPTURE              1064
#define IDC_CHECK_ILLUMINATION_FOR_CAPTURE 1065
#define IDC_CHECK_DECODE_SESSION_STATUS_CHANGE_EVENT 1065
#define IDC_EDIT_wb_blue_temp           1066
#define IDC_EDIT_wb_red_temp            1067
#define IDC_BUTTON_wb_get               1068
#define IDC_BUTTON_wb_set               1069
#define IDC_EDIT_DECODE_DATA            1070
#define IDC_BUTTON_CLEAR_LOG            1071
#define IDC_CHECK_DETECT_BOUNDING_BOX   1072
#define IDC_EDIT_EVENT_LOG              1073
#define IDC_SCROLLBAR1                  1074
#define IDC_EDIT_DECODE_DATA2           1074
#define IDC_EDIT_WEIGHT_DATA            1074
#define IDC_CHECK_DECODE_SESSION_STATUS_CHANGE_EVENT2 1075
#define IDC_CHECK_ERROR_SESSION_STATUS_EVENT 1075
#define IDC_EDIT2                       1076
#define IDC_EDIT_WEIGHT_DATA2           1076
#define IDC_EDIT_CAMERA_STREAM          1076
#define IDC_EDIT_CAMERA_STREA0M         1076
#define IDC_BUTTON_REBBOTCHECK          1078
#define IDC_BUTTON4                     1079
#define IDC_BUTTON_RETRIEVE_CONFIG      1079
#define IDC_BUTTON_LOAD_CONFIG          1080
#define IDC_BUTTON_SET_BACKGROUND       1082
#define IDC_PICTURE_DEVICE_AWAKE_STATUS 1083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
